@startuml
start
split
partition "Проверка ограничения пропускной способности" {
  fork
    :Ограничить\nпропускную способности до 1 Гбит/с\nс помощью tc-netem;
    :Запустить iperf-клиент\nна Loopback;
    :Проверить, что пропускная способность\nне больше 1 Гбит/с;
  fork again
    :Запустить iperf-сервер\nна Loopback;
  end fork
}
split again
partition "Проверка потери пакетов" {
  :Установить потерю 25% пакетов\nс помощью tc-netem;
  :Послать 10 ICMP-ping пакетов с помощью ping;
  :Проверить, что потерялось около 25% пакетов;
}
split again
partition "Проверка задержки пакетов" {
  :Послать 10 ICMP-ping пакетов с помощью ping;
  :Сохранить времена задержки пакетов;
  :Установить задержку пакетов на 100 мс\nс помощью tc-netem;
  :Послать 10 ICMP-ping пакетов с помощью ping;
  :Сохранить времена задержки пакетов;
  :Проверить, что времена задержки\nувеличились примерно на 100 мс;
}
end split
stop
@enduml
